/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatesRouteImport } from './routes/dates'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as WishlistRouteImport } from './routes/wishlist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatesRoute = DatesRouteImport.update({
  id: '/dates',
  path: '/dates',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dates': typeof DatesRoute
  '/finance': typeof FinanceRoute
  '/gifts': typeof GiftsRoute
  '/goals': typeof GoalsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/restaurants': typeof RestaurantsRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dates': typeof DatesRoute
  '/finance': typeof FinanceRoute
  '/gifts': typeof GiftsRoute
  '/goals': typeof GoalsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/restaurants': typeof RestaurantsRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dates': typeof DatesRoute
  '/finance': typeof FinanceRoute
  '/gifts': typeof GiftsRoute
  '/goals': typeof GoalsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/restaurants': typeof RestaurantsRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dates'
    | '/finance'
    | '/gifts'
    | '/goals'
    | '/home'
    | '/login'
    | '/movies'
    | '/plans'
    | '/profile'
    | '/register'
    | '/restaurants'
    | '/wishlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dates'
    | '/finance'
    | '/gifts'
    | '/goals'
    | '/home'
    | '/login'
    | '/movies'
    | '/plans'
    | '/profile'
    | '/register'
    | '/restaurants'
    | '/wishlist'
  id:
    | '__root__'
    | '/'
    | '/dates'
    | '/finance'
    | '/gifts'
    | '/goals'
    | '/home'
    | '/login'
    | '/movies'
    | '/plans'
    | '/profile'
    | '/register'
    | '/restaurants'
    | '/wishlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatesRoute: typeof DatesRoute
  FinanceRoute: typeof FinanceRoute
  GiftsRoute: typeof GiftsRoute
  GoalsRoute: typeof GoalsRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MoviesRoute: typeof MoviesRoute
  PlansRoute: typeof PlansRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RestaurantsRoute: typeof RestaurantsRoute
  WishlistRoute: typeof WishlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dates': {
      id: '/dates'
      path: '/dates'
      fullPath: '/dates'
      preLoaderRoute: typeof DatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatesRoute: DatesRoute,
  FinanceRoute: FinanceRoute,
  GiftsRoute: GiftsRoute,
  GoalsRoute: GoalsRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MoviesRoute: MoviesRoute,
  PlansRoute: PlansRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RestaurantsRoute: RestaurantsRoute,
  WishlistRoute: WishlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
